### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by coylen** [Rodemfr/MicronetToNMEA#1]
Thanks for sharing with me,
you are obviously a real programmer it puts my efforts hacking things together to shame.

Will take me a while to absorb your approach and see what I can learn from your great work.

A few things I have noticed straight of the bat, have you added the following functions to the CC1101 library you are using or maybe it is just a different library version?  

```
int CC1101Driver::GetRxFifoNbBytes()
void CC1101Driver::ReadRxFifo(uint8_t *rxBuffer, int nbBytes)
void CC1101Driver::RestartRx()
```

One thing I have noticed that may help you is in your main.cpp line 146:
`gRfReceiver.setPQT(0); `

I have found that by setting this to 4 rather than 0 then because it enforces a good preamble before accepting data that it stops all the random invalid messages that it picks up because it thinks it sees the sync word.  I know that you have these filtered out later when you check the sentence for validity, but it maybe better to let the radio hardware do this filtering for you?

Neil

**Comment by Rodemfr** [comment]
I'm now using CC1101 Driver from Arduino stock librairies. The few operations that are unsupported are done by directly writing/reading CC1101 registers with the SPI functions.
