### ISSUE TITLE
Operation without master prevents $INHDG transmit

### ISSUE THREAD

**Issue by dwarning** [Rodemfr/MicronetToNMEA#20]
I used master branch with T4.1 and nmea output over serial wifi link. As long I have switched on the display everything is OK - heading from compass is shown on display and in openCPN. Switching off the display all values in openCPN from GPS are OK, except the course because no heading sentences are transferred over the link.

**Comment by Rodemfr** [comment]
The latest changes of NMEA handling should now solve this issue. If you confirm it to me, I will close the issue.

**Comment by dwarning** [comment]
I can confirm HDG sentences are shown if display (master) is OFF.
