### ISSUE TITLE
Use XDR instead of XDG

### ISSUE THREAD

**Issue by dwarning** [Rodemfr/MicronetToNMEA#26]
I searched for NMEA XDG sentence description and found nothing. But XDR is used with "V" specifier in openCPN manual for battery level.

**Comment by Rodemfr** [comment]
Agree, I think I made a strange mix between HDG and XDR...
Looking deeper to OpenCPN doc I saw that Engine Dashboard plugin uses XDR with "BATTERY#0" name instead of "BATTERY" as MTN does today. So I will modify the sentence this way : 
`$INXDR,U,<voltage>,V,BATTERY#0,*<CS>`
This should make it visible to OpenCPN.

I will also replace HDG sentence by HDM. I noticed that dashboard plugin understands HDM and HDT but not HDG.

**Comment by dwarning** [comment]
Regarding HDG - HDM: It is not well documented but qtVlm and avnav seems to decode both, openCPN only HDM.
It is preferable to use HDM to save some traffic because we haven't deviation and variation data available.
I will check it if you made the change.

**Comment by dwarning** [comment]
I want add: All 3 investigated programs, opencpn, avnav and qtvlm show correct boat direction with the old HDG sentences. COG was 0 for this test case. opencpn's dashboard plug "GNSS Compass" show no reaction, this seems the mentioned problem. But as I said boat direction depends correct from HDG values.

BTW: I am using my old compass code. No success with your approach. Very large constant deviation of about 90deg.

**Comment by Rodemfr** [comment]
Thanks for feedback. I'm back home now, I will fix it this week.
Concerning compass code, my compass is correct which means the problem you have is proper to LSM303DLHC (I have a DLH). I will order a DLHC to be sure to fix it properly.

**Comment by dwarning** [comment]
> I will also replace HDG sentence by HDM. I noticed that dashboard plugin understands HDM and HDT but not HDG.

What is the problem with dashboard plugin? Can you explain.
If I activate "Mag HDG" in the plugin I see the values very well, same as the NMEA HDG values.
The "GNSS Compass" will only react with COG different from 0, I belief.

**Comment by Rodemfr** [comment]
You are right for HDG vs HDM : no more problems with OpenCPN !?
I suppose I had something wrong with my setup when I tested... So I won't chagne HDG to HDM so far.

**Comment by dwarning** [comment]
Yes, and just in case you need HDM or HDT for openCPN you can use the 
plugin NmeaConverter to generate the sentences.

Am 31.10.22 um 14:22 schrieb Rodemfr:

**Comment by Rodemfr** [comment]
Done
