### ISSUE TITLE
esp32-trial - does this branch work?

### ISSUE THREAD

**Issue by j-lang** [Rodemfr/MicronetToNMEA#3]
Thanks for this great development. 
Because a ESP32 board ist available and also a CS1101 868MHz board, I tried to compile the esp32-trial branch. 
Due to the notice in the documentation, that there are some issues with the esp32 implementation, I want to know, is the ESP32- branch will work? 
After building the code there are most of the time CS1101 not available errors and the board has to be rebooted. 
Therefore it would be great to know, if the code should work in general, or it absolutely necessary to buy a Teensy board?

**Comment by dwarning** [comment]
No, the branch did not work. It was an experiment.

Teensy board is preferable.

**Comment by j-lang** [comment]
Thanks, I got in the meantime a Teensy board and it works.

**Comment by dwarning** [comment]
No, the branch did not work. It was an experiment.

Teensy board is preferable.

Am 28.03.22 um 22:33 schrieb j-lang:
