### ISSUE TITLE
Add depth offset to NMEA DPT sentence

### ISSUE THREAD

**Issue by tvr256** [Rodemfr/MicronetToNMEA#65]
Currently MTN always reports a depth offset of 0.0 in the NMEA DPT sentence (ie it always reports transducer depth)

There's a setting in Micronet to input the depth offset, which allows you to set depth below surface or depth below keel. Would it be possible to capture this (in the same way as we capture compass offset) and add it to the DPT sentence?

**Comment by Rodemfr** [comment]
It is possible. It will be done tonight.

**Comment by Rodemfr** [comment]
Done. Tested with OpenCPN : transducer offset is correctly interpreted by OCPN.

**Comment by tvr256** [comment]
I don't have my depth sensor at home so I can't test, but reading the code it looks like an extra comma might have been added to the end of the sentence by mistake?

**Comment by Rodemfr** [comment]
`"$INDPT,%.1f,%.1f,"`

**Comment by tvr256** [comment]
You're absolutely correct. Apologies - I was only comparing against the previous DPT readout, I didn't check the spec.

There are a few unofficial versions of the NMEA spec floating around on the internet, some of which contradict each other. The only official one I've found is v3.0.1 from 2002 : https://www.plaisance-pratique.com/IMG/pdf/NMEA0183-2.pdf And this definitely includes the extra range scale parameter.

**Comment by Rodemfr** [comment]
An official spec of NMEA ! I downloaded it. I will use it as reference now and review all the sentences encoded/decoded by MTN.
