### ISSUE TITLE
few quirks

### ISSUE THREAD

**Issue by dwarning** [Rodemfr/MicronetToNMEA#67]
There is a non ansi character on line 215 in CC1101Driver.cpp and is complained by Arduino IDE.

Is it right?
`#define COMPASS_SOURCE_LINK LINK_COMPASS   // Heading data (MTW)
`
MTW - for water temp now comes from Compass?

You can close it immediately after inspection.

**Comment by tvr256** [comment]
I already added a comment to the commit, I think Rodem meant to change the Sea Temp line to MTW, not the Heading line.

**Comment by Rodemfr** [comment]
Ooops, will be fixed tonight. Thanks for all your testing and reviews.

**Comment by Rodemfr** [comment]
Done
