### ISSUE TITLE
Display Depth offset in MTN menu 1

### ISSUE THREAD

**Issue by tvr256** [Rodemfr/MicronetToNMEA#68]
When debugging compass calibration, it was *really* useful to see the compass offset in the MTN menu. Now that we've added the depth offset to https://github.com/Rodemfr/MicronetToNMEA/issues/65 , can we also display the depth offset in the menu?

As a general point, if you change **any** calibration offsets in Micronet while MTN isn't running, the new settings aren't saved to MTN. It's very easy to end up with a mismatch between Micronet and MTN, so the menu display is really useful.

**Comment by Rodemfr** [comment]
Done !
