### ISSUE TITLE
Visual Studio configuration will not load

### ISSUE THREAD

**Issue by tvr256** [Rodemfr/MicronetToNMEA#75]
I followed the instructions to install Visual Studio Code on Windows.

On first start, the PlatformIO installer hangs with the following error message:

```
[2/7/2023, 4:31:48 PM] Unable to resolve configuration with compilerPath: "/home/ronan/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc"
[2/7/2023, 4:31:48 PM] Unable to resolve configuration with compilerPath: "/home/ronan/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc"
```

![image](https://user-images.githubusercontent.com/117984987/217307580-661e4c54-f89c-4e38-9780-72eb89061212.png)

**Comment by j-lang** [comment]
Is it necessary to copy  the **.clang-format** file into the project directory?

**Comment by Rodemfr** [comment]
Yes, if you plan to use clang-format extension to auto-format the code. This is where the extension search for it.

**Comment by tvr256** [comment]
Works great now you've removed your .vscode directory. Thanks for the quick fix.

What's the difference between `PlatformIO: Build` and `PlatformIO: Build (teensy40)`? They both appear to build the Teensy 4.0 configuration:

![image](https://user-images.githubusercontent.com/117984987/217347056-a0b6952e-6c82-46d3-b72a-d2cbf8b22e55.png)

![image](https://user-images.githubusercontent.com/117984987/217347366-7f6826d2-6cc9-4fb6-bf7d-b77dee89098d.png)

**Comment by Rodemfr** [comment]
To be honest, I don't know. I suppose that you could have a software that you can compile for several targets and that you could choose which one to compile... not sure.

**Comment by tvr256** [comment]
I think I've found the answer - `Build` will build all environments (unless a default set of environments is defined). `Build (Teensy40)` will just build the Teensy40 environment. In our case, we only have one environment defined so the result is the same.

https://docs.platformio.org/en/latest/projectconf/sections/platformio/options/generic/default_envs.html

**Comment by j-lang** [comment]
yes, and you can add your setting for e.g. teensy 4.1 to the platformio.ini and set all your conditions for your config in the code (boardconfig.h).
I have a Teensy 4.1 only wired with breadboard wires for testing and a PCB with a Teensy 4.0 ->  just switch to the right environment and build.
