### ISSUE TITLE
Wireless serial devices for NMEA link (BT or WiFi) - which ESP8266 firmware

### ISSUE THREAD

**Issue by j-lang** [Rodemfr/MicronetToNMEA#78]
Is there any advice, which firmware is working as a WiFi serial gateway for OpenCPN or similar application? 
What are the main points to get the inteface running.
Thx Hannes

**Comment by dwarning** [comment]
These both alternatives working with my Serial WiFi v1.0 board:

ESP8266_NMEA_BRIDGE.ino:
http://forward.com.au
// V1.1.0
// 2022/01/11 V1.1.0 added DHCP server to AccessPoint

nmea_bridge.ino:
https://github.com/alvra/nmea-bridge

Dietmar

**Comment by j-lang** [comment]
Great, thank you. I will test it within the next days.

**Comment by Rodemfr** [comment]
Transferring to discussions...
